<?php
/**
 * 获取微信用户信息
 * Date: 2018/11/18
 * Time: 19:32
 */
namespace Wechat\Services\User\Integration;

use Frameworks\Services\Basic\Processor\BaseWorkProcessor;
use Wechat\Tool\WechatTool;

class WechatUserInfoIntegration extends BaseWorkProcessor
{
    protected $openId = '';
    protected $wechat = null;

    public function __construct($openId, $account = '')
    {
        $this->openId = $openId;
        $this->wechat = new WechatTool($account);
    }

    public function process()
    {
        parent::process(); // TODO: Change the autogenerated stub
    }
}