<?php
/**
 * 用户注册
 * Date: 2018/11/18
 * Time: 16:56
 */
namespace Admin\Services\User\Integration;

use Frameworks\Services\Basic\Processor\BaseWorkProcessor;

class UserRegisterIntegration extends BaseWorkProcessor
{
    protected $userData = [];

    public function _init($userData)
    {
        $this->userData = $userData;
    }

    public function process()
    {
        parent::process(); // TODO: Change the autogenerated stub
    }
}