<?php
/**
 * 授权跳转
 * Date: 2018/10/26
 * Time: 17:43
 */
namespace App\Http\Wechat\Actions\Oauth;

use Wechat\Actions\BaseAction;

class RedirectAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}
